---
title: "Logistic Regression"
author: "Filipp Krasovsky"
date: "12/6/2020"
output: html_document
---
```{r}
titanic.data <- read.csv('train.csv')
```

```{r}
View(titanic.data)
```

```{r}
#check for missing values and how many unique values there are
#there are 177 missing age values.
sapply(titanic.data,function(x) sum (is.na(x)))
```

```{r}
#check for unique values.
sapply(titanic.data,function(x) length(unique(x)))
```

```{r}
#plot missing values using the Amelia package
if ("Amelia" %in% rownames(installed.packages())==FALSE){
  install.packages("Amelia")
}
library("Amelia")
```

```{r}
missmap(titanic.data,main="Missing values vs obsvered")
#reveals that 2% of age values are missing.
```

```{r}
#interpolate missing age values with the mean age
#the na.rm indicates that we remove null values in mean calculation.
titanic.data$Age[is.na(titanic.data$Age)] <- mean(titanic.data$Age,na.rm = T)

#subset to relevant variables.
titanic.data <- subset(titanic.data,select=c(2,3,5,6,7,8,10,12))

```

```{r}
#creating the train and test dataset
train <- titanic.data[1:800,]
test  <- titanic.data[801:891,]

#training. we use family=binomial to indicate one of two outcomes.
model <- glm(Survived ~. , family=binomial(link="logit"),data=train)

#output demonstrates that class, sex, age, and sibsp determine survival rates.
#fare and embarked are also not important. since the coefficient for sexmale is #negative, mean are less likely to survive on the titanic.survival decreases with age as well as lower class.
summary(model)
```

```{r}
#performance evaluation
fitted.results <- predict(model,newdata=subset(test,select=c(2,3,4,5,6,7,8)),type='response')

#define survival as 1 or 0 from logit function
fitted.results<- ifelse(fitted.results > 0.5, 1, 0)

misClasificError <- mean(fitted.results != test$Survived)
print(paste('Accuracy',1-misClasificError))

#the model is about 85% accurate.
```

```{r}
#visualization
if ("ROCR" %in% rownames(installed.packages())==FALSE){
  install.packages("ROCR")
}
library(ROCR)

p<-predict(model,newdata=subset(test,select=c(2,3,4,5,6,7,8)),type="response")
pr<-prediction(p,test$Survived)
prf<-performance(pr,measure="tpr",x.measure="fpr")
plot(prf)
auc<-performance(pr,measure="auc")

```

The ROC curve is generated by plotting the true positive and false positive rates at different threshold settings, and the AUC is the area under the curve. A good model has an AUC closer to 1 than 0.5. If the ROC curve is initially steep, more true positives occur than false ones.